### ISSUE TITLE
Typescript template is not working

### ISSUE THREAD

**Issue by dtqs** [nomi9995/expo-library#2]
I've tried to create project using `expo-library` cli

init command failed:
```
? Package Name my-lib
? Package Description my-lib-on-typescript
? Author's GitHub Handle dtqs
? GitHub Repo Path dtqs/my-lib
? License MIT
? Package Manager yarn
? Template typescript
⠋ Copying typescript template to /Users/dtqs/projects/my-lib
✔ Copying typescript template to /Users/dtqs/projects/my-lib

Initializing npm dependencies. This will take a minute.

✖ Running yarn install in root directory
Error: Command failed with exit code 1: yarn install
warning expo-yarn-workspaces > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning expo-yarn-workspaces > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
/bin/sh: line 0: cd: ./example: No such file or directory
error Command failed with exit code 1.
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ cd ./example && expo-yarn-workspaces postinstall
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at makeError (/Users/dtqs/.nvm/versions/node/v12.16.1/lib/node_modules/expo-library/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/dtqs/.nvm/versions/node/v12.16.1/lib/node_modules/expo-library/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async pEachSeries (/Users/dtqs/.nvm/versions/node/v12.16.1/lib/node_modules/expo-library/node_modules/p-each-series/index.js:8:3) {
  shortMessage: 'Command failed with exit code 1: yarn install',
  command: 'yarn install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.22.4\n' +
    'info No lockfile found.\n' +
    '[1/4] Resolving packages...\n' +
    '[2/4] Fetching packages...\n' +
    '[3/4] Linking dependencies...\n' +
    '[4/4] Building fresh packages...\n' +
    'success Saved lockfile.\n' +
    '$ cd ./example && expo-yarn-workspaces postinstall\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: 'warning expo-yarn-workspaces > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\n' +
    'warning expo-yarn-workspaces > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated\n' +
    '/bin/sh: line 0: cd: ./example: No such file or directory\n' +
    'error Command failed with exit code 1.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

As result I've tried to copy example template from git repo.

Running it from `example` folder `yarn start` and pressing in metro interface `Run in web browser` gives: 

``` 
web  Failed to compile.
/Users/dtqs/projects/my-lib/node_modules/my-lib/index.tsx 8:6
Module parse failed: Unexpected token (8:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const { text } = this.props;
|     return (
>       <View>
|         <Text>{text}</Text>
|       </View>
```

**Comment by nomi9995** [comment]
@dtqs can you try againt and let me know?

**Comment by jhankevin** [comment]
I have the same error, any solution?

**Comment by lostchopstik** [comment]
Same problem with the `default` template. Looks like the **examples** folder is not being created.
